# This file will be joined with docker-compose.app.yml from dcape
# See https://github.com/dopos/dcape

services:
  app:
    user: 1000:1000
    volumes:
      - ./data:/wiki/data
    environment:
      - PUID=1000
      - PGID=1000